version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - markmcdowell
  ignore:
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
    - 9.1.1
  - dependency-name: css-loader
    versions:
    - 5.2.4
  - dependency-name: y18n
    versions:
    - 4.0.1
  commit-message:
    prefix: chore
    include: scope
